# Generated by Django 4.0.2 on 2022-02-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Coding', (('Python Development', 'Python Development'), ('JavaScript Development', 'JavaScript Development'), ('TypeScript Development', 'TypeScript Development'))), ('Full-Stack', (('Django Development', 'Django Development'),)), ('Frontend', (('ReactJs Development', 'ReactJs Development'), ('NextJs Development', 'NextJs Development'))), ('RESTFUL', (('Node-Express Development', 'Node-Express Development'), ('Graphql Development', 'Graphql Development'), ('Django REST Development', 'Django REST Development'))), ('Mobile', (('React-Native Development', 'React-Native Development'),)), ('DevOps', (('Docker Development', 'Docker Development'), ('Kubernetes Development', 'Kubernetes Development'), ('Cloud Development', 'Cloud Development')))], max_length=200)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
